{
 "title": "Backend Services Overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(http_requests_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(http_request_duration_seconds_sum[1m])\n)\n/\nsum by (job) (\n  rate(http_request_duration_seconds_count[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (job) (\n  http_requests_total\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status_code) (\n  rate(http_requests_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Route",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (route) ( rate(http_requests_total[1m]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job)(\n  rate(http_requests_total{status_code=~\"4..|5..\"}[1m])\n)\nor\n(\n  0 * sum by(job)(http_requests_total)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}