{
 "title": "Node.js Default Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(process_cpu_seconds_total[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job)(\n  process_resident_memory_bytes\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job)(\n  nodejs_heap_size_used_bytes\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum by(job)(\n  nodejs_heap_size_used_bytes\n)\n/\nsum by(job)(\n  nodejs_heap_size_total_bytes\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 *\nmax by(job)(\n  nodejs_eventloop_lag_p99_seconds\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(job)(\n  time() - process_start_time_seconds\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}