# Use the official stable MySQL 8.0 image
FROM mysql:8.0

# ENV MYSQL_ROOT_PASSWORD=password
# ENV MYSQL_DATABASE=transcendence
# ENV MYSQL_USER=database_user
# ENV MYSQL_PASSWORD=database_password
# ENV MYSQL_PORT=3306

# COPY init/*.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
